35 drink info
Party-of-Five/gitDrunk pull request #61
Opened 2020-06-04 04:38 UTC by Cranekick50

#35

2020-06-04 09:47 UTC, juanlajara requested changes
These appear to be far to many if statements. Let’s sync up and try to dry it up a bit. Also it appears we have changed the name of drinks array. Let’s align on the variable names to avoid conflicts

2020-06-04 16:03 UTC, Frazerhughes approved these changes

2020-06-04 23:54 UTC, AshleyLerma approved these changes
OMG YAY! I think we can dry it up a bit but this is a HUGE step for MVP!

2020-06-05 00:29 UTC, joshuabogart approved these changes

2020-06-05 00:44 UTC, juanlajara approved these changes

2020-06-05 00:44 UTC, merged